In [1]:
import numpy as np
import time

numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

board =  np.array([[3, 0, 6, 5, 0, 8, 4, 0, 0], 
                    [5, 2, 0, 0, 0, 0, 0, 0, 0], 
                    [0, 8, 7, 0, 0, 0, 0, 3, 1], 
                    [0, 0, 3, 0, 1, 0, 0, 8, 0], 
                    [9, 0, 0, 8, 6, 3, 0, 0, 5], 
                    [0, 5, 0, 0, 9, 0, 6, 0, 0], 
                    [1, 3, 0, 0, 0, 0, 2, 5, 0], 
                    [0, 0, 0, 0, 0, 0, 0, 7, 4], 
                    [0, 0, 5, 2, 0, 6, 3, 0, 0]])

def checker(board, position, number):
    x, y = position
    for i in board[x]:
        if i != 0:
            if i==number:return False
    for i in board:
        if i[y] != 0:
            if i[y]==number:return False
    x = 3*int(x/3)
    y = 3*int(y/3)
    three=board[x:x+3, y:y+3]
    for i in three:
        for j in i:
            if j==0:
                continue
            if j==number:return False
    return True

def sudokusolve():
    for x, row in enumerate(board):
        for y, num in enumerate(row):
            if num!=0:
                continue
            for i in numbers:
                if checker(board, (x, y), i):
                    board[x, y] = i
                    sudokusolve()
            board[x, y] = 0
            return
    print(board)
    print('Time elapsed', str(time.time()-stime), 'seconds')

input('press enter to start')
stime = time.time()           
sudokusolve()

press enter to start
[[3 1 6 5 7 8 4 9 2]
 [5 2 9 1 3 4 7 6 8]
 [4 8 7 6 2 9 5 3 1]
 [2 6 3 4 1 5 9 8 7]
 [9 7 4 8 6 3 1 2 5]
 [8 5 1 7 9 2 6 4 3]
 [1 3 8 9 4 7 2 5 6]
 [6 9 2 3 5 1 8 7 4]
 [7 4 5 2 8 6 3 1 9]]
Time elapsed 0.04105854034423828 seconds
